# PowerShell skriptas projekto struktūros sukūrimui
# Sukuriamas pagrindinis projekto katalogas
$projectName = "ElektrosPrekes"
New-Item -ItemType Directory -Path $projectName

# Nustatome pagrindinį kelią
$rootPath = "./$projectName"

# Duomenų katalogai
$dataPaths = @(
    "data/csv",
    "data/photos/grazinimai",
    "data/photos/apsilankymai",
    "data/templates"
)

# CSV failai
$csvFiles = @(
    "data/csv/klientai.csv",
    "data/csv/elektrikai.csv",
    "data/csv/apsilankymai.csv",
    "data/csv/produktai.csv",
    "data/csv/sandelis.csv",
    "data/csv/saskaitos.csv",
    "data/csv/grazinimai.csv",
    "data/csv/lokacijos.csv"
)

# Šablonų failai
$templateFiles = @(
    "data/templates/saskaita.html",
    "data/templates/grazinimas.html",
    "data/templates/sutartis.html"
)

# Src katalogai
$srcPaths = @(
    "src/ElektrosPrekes.Core/Constants",
    "src/ElektrosPrekes.Core/Domain/Documents/Base",
    "src/ElektrosPrekes.Core/Domain/Documents/Invoice",
    "src/ElektrosPrekes.Core/Domain/Documents/Returns",
    "src/ElektrosPrekes.Core/Domain/Warehouse/Products",
    "src/ElektrosPrekes.Core/Domain/Warehouse/Stock",
    "src/ElektrosPrekes.Core/Domain/Electricians",
    "src/ElektrosPrekes.Core/Interfaces",
    "src/ElektrosPrekes.Core/Services",
    "src/ElektrosPrekes.Infrastructure/Data/Context",
    "src/ElektrosPrekes.Infrastructure/Data/Repositories",
    "src/ElektrosPrekes.Infrastructure/Data/CSV",
    "src/ElektrosPrekes.Infrastructure/Integration/Scales",
    "src/ElektrosPrekes.Infrastructure/Integration/QR",
    "src/ElektrosPrekes.Infrastructure/Integration/Printing",
    "src/ElektrosPrekes.Infrastructure/Services",
    "src/ElektrosPrekes.Api/Controllers",
    "src/ElektrosPrekes.Api/Middleware",
    "src/ElektrosPrekes.Api/Models",
    "src/ElektrosPrekes.Shared/Constants",
    "src/ElektrosPrekes.Shared/Helpers"
)

# Core projekto failai
$coreFiles = @(
    "src/ElektrosPrekes.Core/Constants/SystemSettings.cs",
    "src/ElektrosPrekes.Core/Constants/ErrorCodes.cs",
    "src/ElektrosPrekes.Core/Constants/ValidationRules.cs",
    "src/ElektrosPrekes.Core/Domain/Documents/Base/BaseDocument.cs",
    "src/ElektrosPrekes.Core/Domain/Documents/Base/DocumentMetadata.cs",
    "src/ElektrosPrekes.Core/Domain/Documents/Base/DocumentValidation.cs",
    "src/ElektrosPrekes.Core/Domain/Documents/Invoice/Invoice.cs",
    "src/ElektrosPrekes.Core/Domain/Documents/Invoice/InvoiceLine.cs",
    "src/ElektrosPrekes.Core/Domain/Documents/Invoice/InvoiceValidation.cs"
)

# Test katalogai
$testPaths = @(
    "tests/ElektrosPrekes.UnitTests/Core/DocumentTests",
    "tests/ElektrosPrekes.UnitTests/Core/WarehouseTests",
    "tests/ElektrosPrekes.UnitTests/Core/ElectricianTests",
    "tests/ElektrosPrekes.UnitTests/Infrastructure/DataTests",
    "tests/ElektrosPrekes.UnitTests/Infrastructure/IntegrationTests",
    "tests/ElektrosPrekes.IntegrationTests"
)

# Dokumentacijos katalogai
$docPaths = @(
    "docs/architecture",
    "docs/api",
    "docs/deployment"
)

# Įrankių katalogai ir failai
$toolPaths = @(
    "tools/deployment",
    "tools/migration",
    "tools/maintenance"
)

$toolFiles = @(
    "tools/deployment/install.ps1",
    "tools/deployment/db-setup.sql",
    "tools/deployment/iis-config.ps1",
    "tools/migration/csv-import.ps1",
    "tools/migration/data-cleanup.ps1",
    "tools/migration/validation.ps1",
    "tools/maintenance/backup.ps1",
    "tools/maintenance/cleanup.ps1",
    "tools/maintenance/monitor.ps1"
)

# Kuriame visus katalogus
foreach ($path in ($dataPaths + $srcPaths + $testPaths + $docPaths + $toolPaths)) {
    New-Item -ItemType Directory -Path "$rootPath/$path" -Force
}

# Kuriame visus failus
foreach ($file in ($csvFiles + $templateFiles + $coreFiles + $toolFiles)) {
    New-Item -ItemType File -Path "$rootPath/$file" -Force
}

# Sukuriame pagrindinį solution failą
New-Item -ItemType File -Path "$rootPath/$projectName.sln" -Force

# Sukuriame .gitignore failą
$gitignoreContent = @"
## Ignore Visual Studio temporary files, build results, and
## files generated by popular Visual Studio add-ons.

# User-specific files
*.suo
*.user
*.userosscache
*.sln.docstates

# Build results
[Dd]ebug/
[Dd]ebugPublic/
[Rr]elease/
[Rr]eleases/
x64/
x86/
build/
bld/
[Bb]in/
[Oo]bj/

# Visual Studio cache/options directory
.vs/

# MSTest test Results
[Tt]est[Rr]esult*/
[Bb]uild[Ll]og.*

# NUNIT
*.VisualState.xml
TestResult.xml

# Build Results of an ATL Project
[Dd]ebugPS/
[Rr]eleasePS/
dlldata.c

# .NET Core
project.lock.json
project.fragment.lock.json
artifacts/
**/Properties/launchSettings.json

# Files built by Visual Studio
*_i.c
*_p.c
*_i.h
*.ilk
*.meta
*.obj
*.pch
*.pdb
*.pgc
*.pgd
*.rsp
*.sbr
*.tlb
*.tli
*.tlh
*.tmp
*.tmp_proj
*.log
*.vspscc
*.vssscc
.builds
*.pidb
*.svclog
*.scc

# Visual Studio profiler
*.psess
*.vsp
*.vspx
*.sap

# ReSharper
_ReSharper*/
*.[Rr]e[Ss]harper
*.DotSettings.user

# Visual Studio code coverage results
*.coverage
*.coveragexml

# NuGet Packages
*.nupkg
# The packages folder can be ignored because of Package Restore
**/packages/*
# except build/, which is used as an MSBuild target.
!**/packages/build/
# NuGet v3's project.json files produces more ignorable files
*.nuget.props
*.nuget.targets

# Visual Studio cache files
# files ending in .cache can be ignored
*.[Cc]ache
# but keep track of directories ending in .cache
!*.[Cc]ache/

# Others
ClientBin/
~$*
*~
*.dbmdl
*.dbproj.schemaview
*.jfm
*.pfx
*.publishsettings
orleans.codegen.cs
"@

Set-Content -Path "$rootPath/.gitignore" -Value $gitignoreContent

Write-Host "Projekto struktūra sėkmingai sukurta kataloge: $rootPath"
